# https://taskfile.dev

version: '3'

tasks:
  build:
   desc: Build the NixOS configuration for the current host
   cmds:
      - nixos-rebuild build --flake .
  lint:
    desc: Lint the files
    cmds:
      - bash -c "shopt -s globstar && nixfmt **/*.nix"
  switch:
    desc: Switch to the NixOS configuration for the current host
    cmds:
      - sudo nixos-rebuild switch --flake .
  boot:
    desc: Set new configuration for next boot
    cmds:
      - sudo nixos-rebuild boot --flake .
  update:
    desc: Update dependencies and lock file
    cmds:
      - nix flake update
  optimize:
    desc: Optimize the nix store
    cmds:
      - sudo nix-store --optimize
  gc:
    desc: Aggressive GC of the nix store (will delete all unused generations)
    cmds:
      - sudo nix-collect-garbage -d
  repair:
    desc: Repair the nix store
    cmds:
      - sudo nix-store --verify --check-contents --repair
